### PR TITLE
(tests) ngMocks.defaultMock

### PR DESCRIPTION
**Pull request by satanTime**
Hi @siovene,

last time I found some cool things, that might be implemented to facilitate tests in angular projects like yours: default mocks, easy testing of interceptors and guards, extending mock instances instead of overriding them.

I've added these things to `ng-mocks` and applied some in your projects.
Feel free to ask any questions, or to close the PR if it's too big or doesn't fit.

Any feedback is welcome.

Thanks in advance and happy coding!

### CODE REVIEW

**Comment by siovene** [comment]
@satanTime thanks, this is awesome! I love how there's not more need for `testAppImports`. This makes the test suite much more maintainable!

I have a problem tho, I can't run these tests locally. They run on CI just fine, so I don't know what I could be missing.

I checkout your code, removed node_modules and ran `npm ci` again, but I get this error on most tests:

```
Error: This constructor is not compatible with Angular Dependency
Injection because its dependency at index 0 of the parameter list is invalid.
This can happen if the dependency type is a primitive like a string or if an
ancestor of this class is missing an Angular decorator.

Please check that 1) the type for the parameter at index 0 is correct and
2) the correct Angular decorators are defined for this class and its ancestors.
```

For instance at `src/app/shared/services/user-subscription/user-subscription.service.spec.ts:17:23`:

    service = TestBed.inject(UserSubscriptionService);

Any ideas?

**Comment by satanTime** [comment]
Hi @siovene,

thanks for the feedback!

I'll take a look at the issue today. I ran the build commands directly, not via `npm ci`, maybe that's the key.

**Comment by siovene** [comment]
`npm ci` is not to run the build, but to install the npm dependencies using the locked versions in `package-lock.json` :)

**Comment by siovene** [comment]
@satanTime nevermind, something was wrong with my env. I cleaned and installed again and now the tests are green locally too.

**Review by siovene — CHANGES_REQUESTED** [review]
There's 11 more occurrences left of `TestBed.configureTestingModule`.  Most of them don't import/provide anything. Could you please get rid of them too so I don't have any "old style" test code to copy from when I do new components?

**Comment by satanTime** [comment]
Yep, sure, I'll take care about that.

**Comment by satanTime** [comment]
Done!

**Review by siovene — APPROVED** [review]
Awesome, thank you so much!

**Pull request merged**
