### PR TITLE
(deps) Upgrade Angular to 13.0.2

### PR DESCRIPTION
**Pull request by siovene**

### CODE REVIEW

**Comment by siovene** [comment]
@satanTime would you be able to help and figure out why most test don't work anymore after trying to upgrade Angular from 12 to 13?

The app runs fine (all Cypress tests are green) so it must be a configuration setting.

The issue is with ngrx store, I believe, because every time I do this in a test:

```js
import { MockStore } from "@ngrx/store/testing";

const store: MockStore = TestBed.inject(MockStore);
```

I get the following error:

```
Error: Importing TimeagoModule which does not have a ɵmod property
```

(`TimeagoModule` is something I use, but I don't understand why it would be connected to `ngrx`. Additionally, when I run the app, `timeago` works fine)

Thank you in advance!

**Comment by satanTime** [comment]
Hi @siovene, 

I hope you are doing great. 

I think it belongs to changes in angular 13.0.3. Currently I'm investigating that, but looks like there is not an easy fix, and I need some time to publish a proper on. Hopefully asap. 

Please check that issue on GitHub: https://github.com/ike18t/ng-mocks/issues/1427, maybe its comments'd help until the fix is here.

**Comment by siovene** [comment]
@satanTime ok thanks, I'll wait for that fix. Thank you very much!

**Comment by siovene** [comment]
@satanTime 

> I think it belongs to changes in angular 13.0.3. Currently I'm investigating that, but looks like there is not an easy fix, and I need some time to publish a proper on. Hopefully asap.

But this PR is for 13.0.2. I'm reading on the issue page in your repo that you recommend staying with 13.0.2 until you can release a fix, but I'm not trying to upgrade above 13.0.2. I'm trying from 12 to 13.0.2.

Any other comments?

Thank you very much!

**Comment by satanTime** [comment]
Hi @siovene,

You are right. With <=13.0.2, I expect that the latest ng-mocks will work. 

If it still fails here, I'll take a deeper look at the upcoming weekend.

**Comment by siovene** [comment]
@satanTime just FYI, I don't think this problem is related to ike18t/ng-mocks#1427. Could you take a look when you have time? I understand that I will need to wait after you've addressed ike18t/ng-mocks#1427, no problem :) Thanks!

**Comment by satanTime** [comment]
Hi @siovene,

I've checked the failure.
If you have meant `Importing FormlySelectModule which does not have a ɵmod property`,
then right, we need to wait for a proper fix.

The issue here is that https://github.com/ngx-formly/ngx-formly has been built with the latest Angular 13 and already uses the new definition of declarations.

**Comment by siovene** [comment]
@satanTime thanks for checking! Turns out there were/are multiple dependencies that are not ready for Angular 13 yet :(

**Comment by siovene** [comment]
Blocked by https://github.com/Mawi137/ngx-image-cropper/issues/470

**Pull request closed without merging**
